### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by SmartAree** [GDSC-NITH/CookBook-Hacktoberfest#53]
Hey, I am a little confused about this repository. I want to contribute to the Flutter projects. Can you please guide me? How to contribute to Flutter Buttons?

**Comment by triipaathii** [comment]
Check Flutter folder and see how people have contributed there. Basically, pick a topic like Elevated Button. Read about it from different sources so that you can mention complete information in a readme type file about it
.

**Comment by SmartAree** [comment]
Ok Thankyou so much
